dataset:
  name: 'dataset.parquet'
  categorical_columns: [
    'dri_score', 'psych_disturb', 'cyto_score', 'diabetes', 'hla_match_c_high', 'hla_high_res_8', 'tbi_status',
    'arrhythmia', 'hla_low_res_6', 'graft_type', 'vent_hist', 'renal_issue', 'pulm_severe', 'prim_disease_hct',
    'hla_high_res_6', 'cmv_status', 'hla_high_res_10', 'hla_match_dqb1_high', 'tce_imm_match', 'hla_nmdp_6',
    'hla_match_c_low', 'rituximab', 'hla_match_drb1_low', 'hla_match_dqb1_low', 'prod_type', 'cyto_score_detail',
    'conditioning_intensity', 'ethnicity', 'year_hct', 'obesity', 'mrd_hct', 'in_vivo_tcd', 'tce_match',
    'hla_match_a_high', 'hepatic_severe', 'prior_tumor', 'hla_match_b_low', 'peptic_ulcer', 'hla_match_a_low',
    'gvhd_proph', 'rheum_issue', 'sex_match', 'hla_match_b_high', 'race_group', 'comorbidity_score', 'karnofsky_score',
    'hepatic_mild', 'tce_div_match', 'donor_related', 'melphalan_dose', 'hla_low_res_8', 'cardiac', 'hla_match_drb1_high',
    'pulm_moderate', 'hla_low_res_10'
  ]
  continuous_columns: [
    'donor_age', 'age_at_hct'
  ]
  efs_predictions_path: null

training:
  task: 'classification'
  sample_weight: False
  efs_weight: 1.0
  rank_transform: False
  two_stage: False
  target: 'efs'
  features: [
    'dri_score_encoded', 'psych_disturb_encoded', 'cyto_score_encoded', 'diabetes_encoded', 'hla_match_c_high_encoded',
    'hla_high_res_8_encoded', 'tbi_status_encoded', 'arrhythmia_encoded', 'hla_low_res_6_encoded', 'graft_type_encoded',
    'vent_hist_encoded', 'renal_issue_encoded', 'pulm_severe_encoded', 'prim_disease_hct_encoded', 'hla_high_res_6_encoded',
    'cmv_status_encoded', 'hla_high_res_10_encoded', 'hla_match_dqb1_high_encoded', 'tce_imm_match_encoded', 'hla_nmdp_6_encoded',
    'hla_match_c_low_encoded', 'rituximab_encoded', 'hla_match_drb1_low_encoded', 'hla_match_dqb1_low_encoded', 'prod_type_encoded',
    'cyto_score_detail_encoded', 'conditioning_intensity_encoded', 'ethnicity_encoded', 'year_hct_encoded', 'obesity_encoded',
    'mrd_hct_encoded', 'in_vivo_tcd_encoded', 'tce_match_encoded', 'hla_match_a_high_encoded', 'hepatic_severe_encoded',
    'prior_tumor_encoded', 'hla_match_b_low_encoded', 'peptic_ulcer_encoded', 'hla_match_a_low_encoded', 'gvhd_proph_encoded',
    'rheum_issue_encoded', 'sex_match_encoded', 'hla_match_b_high_encoded', 'race_group_encoded', 'comorbidity_score_encoded',
    'karnofsky_score_encoded', 'hepatic_mild_encoded', 'tce_div_match_encoded', 'donor_related_encoded', 'melphalan_dose_encoded',
    'hla_low_res_8_encoded', 'cardiac_encoded', 'hla_match_drb1_high_encoded', 'pulm_moderate_encoded', 'hla_low_res_10_encoded',
    'donor_age_normalized', 'age_at_hct_normalized'
  ]
  folds: [1, 2, 3, 4, 5, 6, 7]
  loss_function: 'BCEWithLogitsLoss'
  loss_function_args: {}
  weighted_loss_function: False
  training_batch_size: 1024
  test_batch_size: 1024
  num_workers: 16
  random_state: 42
  deterministic_cudnn: False
  device: 'cpu'
  optimizer: 'AdamW'
  optimizer_args:
    lr: 0.001
    betas: [0.9, 0.999]
    weight_decay: 0.001
  lr_scheduler: 'OneCycleLR'
  lr_scheduler_args:
    max_lr: 0.001
    epochs: 10
    steps_per_epoch: 25
    pct_start: 0.025
    anneal_strategy: 'cos'
    div_factor: 10
    final_div_factor: 100
  amp: False
  epochs: 10

model:
  model_class: 'EmbeddingMLP'
  model_args:
    input_n_categories: [
      12,  4,  8,  4,  4,  8,  8,  4,  6,  2,  3,  4,  4, 18,  7,  5,  9,
      4,  9,  6,  4,  3,  3,  4,  2,  6,  7,  4, 13,  4,  3,  3,  5,  4,
      4,  4,  4,  4,  4, 18,  4,  5,  4,  6, 12,  8,  4,  5,  4,  3,  8,
      4,  4,  4,  8
    ]
    input_cont_dim: 2
    embedding_dim: 16
    stem_dim: 128
    mlp_hidden_dim: 512
    n_blocks: 1
    output_dim: 1
  model_checkpoint_path: null

persistence:
  save_best_metrics: ['log_loss']
  save_best_metric_higher_or_lower: ['lower']
  save_epochs: []
