dataset:
  name: 'dataset.parquet'
  categorical_columns: [
    'dri_score', 'psych_disturb', 'cyto_score', 'diabetes', 'tbi_status', 'arrhythmia',
    'graft_type', 'vent_hist', 'renal_issue', 'pulm_severe', 'prim_disease_hct', 'cmv_status',
    'tce_imm_match', 'rituximab', 'prod_type', 'cyto_score_detail', 'conditioning_intensity',
    'ethnicity', 'obesity', 'mrd_hct', 'in_vivo_tcd', 'tce_match', 'hepatic_severe', 'prior_tumor',
    'peptic_ulcer', 'gvhd_proph', 'rheum_issue', 'sex_match', 'race_group', 'hepatic_mild',
    'tce_div_match', 'donor_related', 'melphalan_dose', 'cardiac', 'pulm_moderate'
  ]

training:
  target: 'kmf_survival_probability'
  features: [
    'dri_score_encoded', 'psych_disturb_encoded', 'cyto_score_encoded', 'diabetes_encoded',
    'hla_match_c_high', 'hla_high_res_8',
    'tbi_status_encoded', 'arrhythmia_encoded', 'hla_low_res_6', 'graft_type_encoded', 'vent_hist_encoded',
    'renal_issue_encoded', 'pulm_severe_encoded', 'prim_disease_hct_encoded', 'hla_high_res_6',
    'cmv_status_encoded',
    'hla_high_res_10', 'hla_match_dqb1_high', 'tce_imm_match_encoded', 'hla_nmdp_6', 'hla_match_c_low',
    'rituximab_encoded', 'hla_match_drb1_low', 'hla_match_dqb1_low', 'prod_type_encoded',
    'cyto_score_detail_encoded', 'conditioning_intensity_encoded', 'ethnicity_encoded',
    'year_hct', 'obesity_encoded', 'mrd_hct_encoded', 'in_vivo_tcd_encoded', 'tce_match_encoded',
    'hla_match_a_high', 'hepatic_severe_encoded', 'donor_age', 'prior_tumor_encoded',
    'hla_match_b_low', 'peptic_ulcer_encoded', 'age_at_hct', 'hla_match_a_low', 'gvhd_proph_encoded',
    'rheum_issue_encoded', 'sex_match_encoded', 'hla_match_b_high', 'race_group_encoded', 'comorbidity_score',
    'karnofsky_score', 'hepatic_mild_encoded', 'tce_div_match_encoded', 'donor_related_encoded',
    'melphalan_dose_encoded', 'hla_low_res_8', 'cardiac_encoded', 'hla_match_drb1_high',
    'pulm_moderate_encoded', 'hla_low_res_10',
  ]
  categorical_features: [
    'dri_score_encoded', 'psych_disturb_encoded', 'cyto_score_encoded', 'diabetes_encoded',
    'tbi_status_encoded', 'arrhythmia_encoded',
    'graft_type_encoded', 'vent_hist_encoded', 'renal_issue_encoded', 'pulm_severe_encoded',
    'prim_disease_hct_encoded', 'cmv_status_encoded',
    'tce_imm_match_encoded', 'rituximab_encoded', 'prod_type_encoded', 'cyto_score_detail_encoded',
    'conditioning_intensity_encoded',
    'ethnicity_encoded', 'obesity_encoded', 'mrd_hct_encoded', 'in_vivo_tcd_encoded', 'tce_match_encoded',
    'hepatic_severe_encoded', 'prior_tumor_encoded',
    'peptic_ulcer_encoded', 'gvhd_proph_encoded', 'rheum_issue_encoded', 'sex_match_encoded', 'race_group_encoded',
    'hepatic_mild_encoded',
    'tce_div_match_encoded', 'donor_related_encoded', 'melphalan_dose_encoded', 'cardiac_encoded', 'pulm_moderate_encoded'
  ]
  folds: [1, 2, 3, 4, 5]
  seeds: [0,]
  rank_transform: False

model_parameters:
  objective: 'cross_entropy_lambda'
  boosting_type: 'gbdt'
  data_sample_strategy: 'bagging'
  learning_rate: 0.01
  num_leaves: 96
  tree_learner: 'serial'
  num_threads: -1
  device_type: 'cpu'
  seed: null
  bagging_seed: null
  feature_fraction_seed: null
  extra_seed: null
  data_random_seed: null
  deterministic: False
  max_depth: -1
  min_data_in_leaf: 50
  min_sum_hessian_in_leaf: 0
  bagging_fraction: 0.9
  bagging_freq: 1
  feature_fraction: 0.9
  feature_fraction_bynode: 1.
  extra_trees: True
  lambda_l1: 0.
  lambda_l2: 0.
  linear_lambda: 0.
  min_gain_to_split: 0.
  path_smooth: 0.
  max_bin: 255
  min_data_in_bin: 1
  bin_construct_sample_cnt: 200000

fit_parameters:
  boosting_rounds: 600
  log_evaluation: 100
