dataset:
  name: 'dataset.parquet'
  categorical_columns: [
    'dri_score', 'psych_disturb', 'cyto_score', 'diabetes', 'tbi_status', 'arrhythmia',
    'graft_type', 'vent_hist', 'renal_issue', 'pulm_severe', 'prim_disease_hct', 'cmv_status',
    'tce_imm_match', 'rituximab', 'prod_type', 'cyto_score_detail', 'conditioning_intensity',
    'ethnicity', 'obesity', 'mrd_hct', 'in_vivo_tcd', 'tce_match', 'hepatic_severe', 'prior_tumor',
    'peptic_ulcer', 'gvhd_proph', 'rheum_issue', 'sex_match', 'race_group', 'hepatic_mild',
    'tce_div_match', 'donor_related', 'melphalan_dose', 'cardiac', 'pulm_moderate'
  ]
  continuous_columns: [
    'hla_match_c_high', 'hla_high_res_8', 'hla_low_res_6', 'hla_high_res_6', 'hla_high_res_10', 'hla_match_dqb1_high',
    'hla_nmdp_6', 'hla_match_c_low', 'hla_match_drb1_low', 'hla_match_dqb1_low', 'year_hct',
    'hla_match_a_high', 'donor_age', 'hla_match_b_low', 'age_at_hct', 'hla_match_a_low', 'hla_match_b_high',
    'comorbidity_score', 'karnofsky_score', 'hla_low_res_8', 'hla_match_drb1_high', 'hla_low_res_10'
  ]

training:
  time: 'efs_time'
  event: 'efs'
  features: [
    'dri_score_High', 'dri_score_High - TED AML case <missing cytogenetics', 'dri_score_Intermediate',
    'dri_score_Intermediate - TED AML case <missing cytogenetics', 'dri_score_Low', 'dri_score_Missing disease status',
    'dri_score_N/A - disease not classifiable', 'dri_score_N/A - non-malignant indication', 'dri_score_N/A - pediatric',
    'dri_score_TBD cytogenetics', 'dri_score_Very high', 'dri_score_nan', 'psych_disturb_No', 'psych_disturb_Not done',
    'psych_disturb_Yes', 'psych_disturb_nan', 'cyto_score_Favorable', 'cyto_score_Intermediate', 'cyto_score_Normal',
    'cyto_score_Not tested', 'cyto_score_Other', 'cyto_score_Poor', 'cyto_score_TBD', 'cyto_score_nan', 'diabetes_No',
    'diabetes_Not done', 'diabetes_Yes', 'diabetes_nan', 'tbi_status_No TBI', 'tbi_status_TBI + Cy +- Other',
    'tbi_status_TBI +- Other, -cGy, fractionated', 'tbi_status_TBI +- Other, -cGy, single', 'tbi_status_TBI +- Other, -cGy, unknown dose',
    'tbi_status_TBI +- Other, <=cGy', 'tbi_status_TBI +- Other, >cGy', 'tbi_status_TBI +- Other, unknown dose',
    'arrhythmia_No', 'arrhythmia_Not done', 'arrhythmia_Yes', 'arrhythmia_nan', 'graft_type_Bone marrow', 'graft_type_Peripheral blood',
    'vent_hist_No', 'vent_hist_Yes', 'vent_hist_nan', 'renal_issue_No', 'renal_issue_Not done', 'renal_issue_Yes', 'renal_issue_nan',
    'pulm_severe_No', 'pulm_severe_Not done', 'pulm_severe_Yes', 'pulm_severe_nan', 'prim_disease_hct_AI', 'prim_disease_hct_ALL',
    'prim_disease_hct_AML', 'prim_disease_hct_CML', 'prim_disease_hct_HD', 'prim_disease_hct_HIS', 'prim_disease_hct_IEA',
    'prim_disease_hct_IIS', 'prim_disease_hct_IMD', 'prim_disease_hct_IPA', 'prim_disease_hct_MDS', 'prim_disease_hct_MPN',
    'prim_disease_hct_NHL', 'prim_disease_hct_Other acute leukemia', 'prim_disease_hct_Other leukemia', 'prim_disease_hct_PCD',
    'prim_disease_hct_SAA', 'prim_disease_hct_Solid tumor', 'cmv_status_+/+', 'cmv_status_+/-', 'cmv_status_-/+', 'cmv_status_-/-',
    'cmv_status_nan', 'tce_imm_match_G/B', 'tce_imm_match_G/G', 'tce_imm_match_H/B', 'tce_imm_match_H/H', 'tce_imm_match_P/B',
    'tce_imm_match_P/G', 'tce_imm_match_P/H', 'tce_imm_match_P/P', 'tce_imm_match_nan', 'rituximab_No', 'rituximab_Yes',
    'rituximab_nan', 'prod_type_BM', 'prod_type_PB', 'cyto_score_detail_Favorable', 'cyto_score_detail_Intermediate',
    'cyto_score_detail_Not tested', 'cyto_score_detail_Poor', 'cyto_score_detail_TBD', 'cyto_score_detail_nan',
    'conditioning_intensity_MAC', 'conditioning_intensity_N/A, F(pre-TED) not submitted', 'conditioning_intensity_NMA',
    'conditioning_intensity_No drugs reported', 'conditioning_intensity_RIC', 'conditioning_intensity_TBD', 'conditioning_intensity_nan',
    'ethnicity_Hispanic or Latino', 'ethnicity_Non-resident of the U.S.', 'ethnicity_Not Hispanic or Latino', 'ethnicity_nan',
    'obesity_No', 'obesity_Not done', 'obesity_Yes', 'obesity_nan', 'mrd_hct_Negative', 'mrd_hct_Positive', 'mrd_hct_nan',
    'in_vivo_tcd_No', 'in_vivo_tcd_Yes', 'in_vivo_tcd_nan', 'tce_match_Fully matched', 'tce_match_GvH non-permissive',
    'tce_match_HvG non-permissive', 'tce_match_Permissive', 'tce_match_nan', 'hepatic_severe_No', 'hepatic_severe_Not done',
    'hepatic_severe_Yes', 'hepatic_severe_nan', 'prior_tumor_No', 'prior_tumor_Not done', 'prior_tumor_Yes', 'prior_tumor_nan',
    'peptic_ulcer_No', 'peptic_ulcer_Not done', 'peptic_ulcer_Yes', 'peptic_ulcer_nan', 'gvhd_proph_CDselect +- other',
    'gvhd_proph_CDselect alone', 'gvhd_proph_CSA + MMF +- others(not FK)', 'gvhd_proph_CSA + MTX +- others(not MMF,FK)',
    'gvhd_proph_CSA +- others(not FK,MMF,MTX)', 'gvhd_proph_CSA alone', 'gvhd_proph_Cyclophosphamide +- others',
    'gvhd_proph_Cyclophosphamide alone', 'gvhd_proph_FK+ MMF +- others', 'gvhd_proph_FK+ MTX +- others(not MMF)',
    'gvhd_proph_FKalone', 'gvhd_proph_No GvHD Prophylaxis', 'gvhd_proph_Other GVHD Prophylaxis', 'gvhd_proph_Parent Q = yes, but no agent',
    'gvhd_proph_TDEPLETION +- other', 'gvhd_proph_TDEPLETION alone', 'gvhd_proph_nan', 'rheum_issue_No', 'rheum_issue_Not done',
    'rheum_issue_Yes', 'rheum_issue_nan', 'sex_match_F-F', 'sex_match_F-M', 'sex_match_M-F', 'sex_match_M-M', 'sex_match_nan',
    'race_group_American Indian or Alaska Native', 'race_group_Asian', 'race_group_Black or African-American', 'race_group_More than one race',
    'race_group_Native Hawaiian or other Pacific Islander', 'race_group_White', 'hepatic_mild_No', 'hepatic_mild_Not done', 'hepatic_mild_Yes',
    'hepatic_mild_nan', 'tce_div_match_Bi-directional non-permissive', 'tce_div_match_GvH non-permissive', 'tce_div_match_HvG non-permissive',
    'tce_div_match_Permissive mismatched', 'tce_div_match_nan', 'donor_related_Multiple donor (non-UCB)', 'donor_related_Related',
    'donor_related_Unrelated', 'donor_related_nan', 'melphalan_dose_MEL', 'melphalan_dose_N/A, Mel not given', 'melphalan_dose_nan',
    'cardiac_No', 'cardiac_Not done', 'cardiac_Yes', 'cardiac_nan', 'pulm_moderate_No', 'pulm_moderate_Not done', 'pulm_moderate_Yes',
    'pulm_moderate_nan', 'hla_match_c_high_normalized', 'hla_high_res_8_normalized', 'hla_low_res_6_normalized', 'hla_high_res_6_normalized',
    'hla_high_res_10_normalized', 'hla_match_dqb1_high_normalized', 'hla_nmdp_6_normalized', 'hla_match_c_low_normalized',
    'hla_match_drb1_low_normalized', 'hla_match_dqb1_low_normalized', 'year_hct_normalized', 'hla_match_a_high_normalized',
    'donor_age_normalized', 'hla_match_b_low_normalized', 'age_at_hct_normalized', 'hla_match_a_low_normalized', 'hla_match_b_high_normalized',
    'comorbidity_score_normalized', 'karnofsky_score_normalized', 'hla_low_res_8_normalized', 'hla_match_drb1_high_normalized', 'hla_low_res_10_normalized'
  ]
  folds: [1, 2, 3, 4, 5]

model_class: CoxnetSurvivalAnalysis
model_parameters:
  n_alphas: 200
  alphas: null
  alpha_min_ratio: 'auto'
  l1_ratio: 0.5
  normalize: False
