dataset:
  name: 'dataset.parquet'
  categorical_columns: [
    'dri_score', 'psych_disturb', 'cyto_score', 'diabetes', 'tbi_status', 'arrhythmia',
    'graft_type', 'vent_hist', 'renal_issue', 'pulm_severe', 'prim_disease_hct', 'cmv_status',
    'tce_imm_match', 'rituximab', 'prod_type', 'cyto_score_detail', 'conditioning_intensity',
    'ethnicity', 'obesity', 'mrd_hct', 'in_vivo_tcd', 'tce_match', 'hepatic_severe', 'prior_tumor',
    'peptic_ulcer', 'gvhd_proph', 'rheum_issue', 'sex_match', 'race_group', 'hepatic_mild',
    'tce_div_match', 'donor_related', 'melphalan_dose', 'cardiac', 'pulm_moderate'
  ]

training:
  task: 'ranking'
  rank_transform: True
  target: 'log_survival_probability'
  features: [
    'dri_score', 'psych_disturb', 'cyto_score', 'diabetes',
    'hla_match_c_high', 'hla_high_res_8',
    'tbi_status', 'arrhythmia', 'hla_low_res_6', 'graft_type', 'vent_hist',
    'renal_issue', 'pulm_severe', 'prim_disease_hct', 'hla_high_res_6',
    'cmv_status',
    'hla_high_res_10', 'hla_match_dqb1_high', 'tce_imm_match', 'hla_nmdp_6', 'hla_match_c_low',
    'rituximab', 'hla_match_drb1_low', 'hla_match_dqb1_low', 'prod_type',
    'cyto_score_detail', 'conditioning_intensity', 'ethnicity',
    'year_hct', 'obesity', 'mrd_hct', 'in_vivo_tcd', 'tce_match',
    'hla_match_a_high', 'hepatic_severe', 'donor_age', 'prior_tumor',
    'hla_match_b_low', 'peptic_ulcer', 'age_at_hct', 'hla_match_a_low', 'gvhd_proph',
    'rheum_issue', 'sex_match', 'hla_match_b_high', 'race_group', 'comorbidity_score',
    'karnofsky_score', 'hepatic_mild', 'tce_div_match', 'donor_related',
    'melphalan_dose', 'hla_low_res_8', 'cardiac', 'hla_match_drb1_high',
    'pulm_moderate', 'hla_low_res_10',
  ]
  categorical_features: []
  folds: [1, 2, 3, 4, 5]
  seeds: [0,]

model_parameters:
  objective: 'l2'
  boosting_type: 'gbdt'
  data_sample_strategy: 'bagging'
  learning_rate: 0.01
  num_leaves: 64
  tree_learner: 'serial'
  num_threads: 16
  device_type: 'cpu'
  seed: null
  bagging_seed: null
  feature_fraction_seed: null
  extra_seed: null
  data_random_seed: null
  deterministic: False
  max_depth: -1
  min_data_in_leaf: 50
  min_sum_hessian_in_leaf: 0
  bagging_fraction: 0.7
  bagging_freq: 1
  feature_fraction: 0.5
  feature_fraction_bynode: 1.
  extra_trees: False
  lambda_l1: 0.
  lambda_l2: 2
  linear_lambda: 0.
  min_gain_to_split: 0.
  min_data_per_group: 150
  max_cat_threshold: 64
  cat_l2: 10
  cat_smooth: 10
  max_cat_to_onehot: 4
  path_smooth: 0.
  max_bin: 384
  min_data_in_bin: 3
  bin_construct_sample_cnt: 200000
  use_missing: True
  zero_as_missing: False

fit_parameters:
  boosting_rounds: 1000
  log_evaluation: 100
